name: Movies CD

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: "Tag name for APK release"
        required: true
        default: 'v1.0'
      tag_message:
        description: "Release description"
        required: false
        default: 'Latest release'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ inputs.version_name }}
        message: ${{ inputs.tag_message }}

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Prepare local.properties
      id: prepare_local_props
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'local.properties'
        fileDir: '.'
        encodedString: ${{ secrets.LOCAL_PROPERTIES }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Release build
      id: build_release
      run: ./gradlew assembleRelease -PversionName='${{ inputs.version_name }}'

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.MOVIES_KEYSTORE }}
        alias: ${{ secrets.MOVIES_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.MOVIES_KEY_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: List release files
      run: ls ./app/build/outputs/apk/release/

    - name: Rename APK
      id: rename_apk
      run: mv ./app/build/outputs/apk/release/MoviesKt-release-unsigned-signed.apk ./app/build/outputs/apk/release/MoviesKt-${{ inputs.version_name }}.apk

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
#      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ inputs.version_name }}
        name: MoviesKt-${{ inputs.version_name }}
        files: ./app/build/outputs/apk/release/MoviesKt-${{ inputs.version_name }}.apk
